name: Six Workflow
on:
  push:
    branches:
      - master
      - "page/*"
      - "page/**"
      - "!page/blog"
    #tags:
     # -"v1.*"
     #-"!v1.2.1"
    paths:
      - "**.html"


jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event Vars
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF